In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

True

In [2]:
import pandas as pd
import numpy as np
import runregistry as rr
from cmsdials.auth.bearer import Credentials
from cmsdials import Dials
from cmsdials.filters import LumisectionHistogram1DFilters
from tqdm import tqdm

/home/gamoreir/.cache/pypoetry/virtualenvs/ml-examples-EfRPkUGI-py3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
creds = Credentials.from_creds_file()
dials = Dials(creds, workspace="jetmet")

In [4]:
me = "JetMET/MET/pfMETT1/Cleaned/METSig"
runs = [386642, 386640, 385841, 385604, 385422, 385286, 385142, 384243, 384188, 382749, 382213, 380360, 380237, 380195, 379456, 379420, 360950]
dataset_regex = "/JetMET0?/Run202.*-PromptReco-v1/DQMIO"

data = []
for run_number in runs:
    res = dials.h1d.list_all(LumisectionHistogram1DFilters(page_size=500, dataset__regex=dataset_regex, me=me,  run_number=run_number), enable_progress=True)
    df = res.to_pandas()
    data.append(df)

data = pd.concat(data)
data = data.sort_values(by=['run_number', 'ls_number'])


Progress:   0%|          | 0/1 [00:00<?, ?it/s]

Progress: 100%|██████████| 2/2 [00:00<00:00,  4.44it/s]


In [5]:
data

dataset                                 me  \
0     /JetMET/Run2022F-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
1     /JetMET/Run2022F-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
2     /JetMET/Run2022F-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
3     /JetMET/Run2022F-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
4     /JetMET/Run2022F-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
..                                     ...                                ...   
726  /JetMET0/Run2024I-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
727  /JetMET0/Run2024I-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
728  /JetMET0/Run2024I-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
729  /JetMET0/Run2024I-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   
730  /JetMET0/Run2024I-PromptReco-v1/DQMIO  JetMET/MET/pfMETT1/Cleaned/METSig   

     dataset_id      file_id  run_number  ls_number  me_id  x_min  x_max  \
0      14483539   2059624837      360950          1      5    0.0   51.0   
1      14483539   2059624877      360950          2      5    0.0   51.0   
2      14483539   2059624277      360950          3      5    0.0   51.0   
3      14483539   2059624317      360950          4      5    0.0   51.0   
4      14483539   2059624837      360950          5      5    0.0   51.0   
..          ...          ...         ...        ...    ...    ...    ...   
726    15090031  17813673957      386642        728      5    0.0   51.0   
727    15090031  17813673957      386642        729      5    0.0   51.0   
728    15090031  17813673957      386642        730      5    0.0   51.0   
729    15090031  17813673957      386642        731      5    0.0   51.0   
730    15090031  17813673957      386642        732      5    0.0   51.0   

     x_bin  entries                                               data  
0     51.0     7980  [4055.0, 2895.0, 735.0, 212.0, 46.0, 17.0, 9.0...  
1     51.0     8444  [4252.0, 3101.0, 772.0, 222.0, 61.0, 19.0, 8.0...  
2     51.0     8226  [4110.0, 2974.0, 818.0, 228.0, 58.0, 19.0, 15....  
3     51.0     8306  [4156.0, 3053.0, 812.0, 204.0, 44.0, 17.0, 7.0...  
4     51.0     8157  [4053.0, 3006.0, 783.0, 222.0, 60.0, 15.0, 7.0...  
..     ...      ...                                                ...  
726   51.0        0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
727   51.0        0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
728   51.0        0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
729   51.0        0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
730   51.0        0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[14867 rows x 12 columns]

In [6]:
data_arr = np.vstack(data.data)
data_arr

array([[4055., 2895.,  735., ...,    0.,    0.,    0.],
       [4252., 3101.,  772., ...,    0.,    0.,    0.],
       [4110., 2974.,  818., ...,    0.,    0.,    0.],
       ...,
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [7]:
run_arr = data.run_number.to_numpy().astype(np.int32)
run_arr

array([360950, 360950, 360950, ..., 386642, 386642, 386642], dtype=int32)

In [8]:
os.makedirs("../data", exist_ok=True)
np.save(f"../data/data_unfiltered.npy", data_arr)
np.save(f"../data/runs_unfiltered.npy", run_arr)

In [9]:
lumisections = []
for run_number in tqdm(runs):
    if run_number in (360950,):
        rr_dataset = "/PromptReco/Collisions2022/DQM"
    else:
        rr_dataset = "/PromptReco/Collisions2024/DQM"
    joint_ranges = rr.get_joint_lumisection_ranges(run_number, rr_dataset)
    run_lumisections = []
    for joint_range in joint_ranges:
        # Cleanup extra keys in rr lumis, since we only care about the status key
        for key, value in joint_range.items():
            if isinstance(value, dict) and "status" in value.keys():
                joint_range[key] = value["status"] == "GOOD"

        # Repeat the flags for the same range
        start_ls = joint_range.pop("start")
        end_ls = joint_range.pop("end")
        for ls_number in range(start_ls, end_ls + 1):
            run_lumisections.append({"run_number": run_number, "ls_number": ls_number, **joint_range})

    run_lumisections = pd.DataFrame(run_lumisections)
    lumisections.append(run_lumisections)

lumisections = pd.concat(lumisections)

100%|██████████| 17/17 [00:11<00:00,  1.52it/s]


In [10]:
lumis = lumisections[
    lumisections.cms_active &
    lumisections.beam1_stable &
    lumisections.beam2_stable &
    lumisections.beam1_present &
    lumisections.beam2_present &
    lumisections.bpix_ready &
    lumisections.fpix_ready &
    lumisections.tibtid_ready &
    lumisections.tecm_ready &
    lumisections.tecp_ready &
    lumisections.tob_ready &
    lumisections.hbhea_ready &
    lumisections.hbheb_ready &
    lumisections.hbhec_ready &
    lumisections.hf_ready &
    lumisections.ho_ready
]
lumis = lumis[["run_number", "ls_number", "jetmet-jetmet"]]

lumis

run_number  ls_number  jetmet-jetmet
0        386642          1           True
1        386642          2           True
2        386642          3           True
3        386642          4           True
4        386642          5           True
..          ...        ...            ...
713      360950        714           True
714      360950        715           True
715      360950        716           True
716      360950        717           True
717      360950        718           True

[14537 rows x 3 columns]

In [11]:
joint_data = data.merge(lumis, on=['run_number', 'ls_number'])
joint_data

dataset  \
0       /JetMET/Run2022F-PromptReco-v1/DQMIO   
1       /JetMET/Run2022F-PromptReco-v1/DQMIO   
2       /JetMET/Run2022F-PromptReco-v1/DQMIO   
3       /JetMET/Run2022F-PromptReco-v1/DQMIO   
4       /JetMET/Run2022F-PromptReco-v1/DQMIO   
...                                      ...   
14509  /JetMET0/Run2024I-PromptReco-v1/DQMIO   
14510  /JetMET0/Run2024I-PromptReco-v1/DQMIO   
14511  /JetMET0/Run2024I-PromptReco-v1/DQMIO   
14512  /JetMET0/Run2024I-PromptReco-v1/DQMIO   
14513  /JetMET0/Run2024I-PromptReco-v1/DQMIO   

                                      me  dataset_id      file_id  run_number  \
0      JetMET/MET/pfMETT1/Cleaned/METSig    14483539   2059624837      360950   
1      JetMET/MET/pfMETT1/Cleaned/METSig    14483539   2059624877      360950   
2      JetMET/MET/pfMETT1/Cleaned/METSig    14483539   2059624277      360950   
3      JetMET/MET/pfMETT1/Cleaned/METSig    14483539   2059624317      360950   
4      JetMET/MET/pfMETT1/Cleaned/METSig    14483539   2059624837      360950   
...                                  ...         ...          ...         ...   
14509  JetMET/MET/pfMETT1/Cleaned/METSig    15090031  17813674077      386642   
14510  JetMET/MET/pfMETT1/Cleaned/METSig    15090031  17813674077      386642   
14511  JetMET/MET/pfMETT1/Cleaned/METSig    15090031  17813674077      386642   
14512  JetMET/MET/pfMETT1/Cleaned/METSig    15090031  17813674117      386642   
14513  JetMET/MET/pfMETT1/Cleaned/METSig    15090031  17813674117      386642   

       ls_number  me_id  x_min  x_max  x_bin  entries  \
0              1      5    0.0   51.0   51.0     7980   
1              2      5    0.0   51.0   51.0     8444   
2              3      5    0.0   51.0   51.0     8226   
3              4      5    0.0   51.0   51.0     8306   
4              5      5    0.0   51.0   51.0     8157   
...          ...    ...    ...    ...    ...      ...   
14509        720      5    0.0   51.0   51.0     2518   
14510        721      5    0.0   51.0   51.0     2640   
14511        722      5    0.0   51.0   51.0     2627   
14512        723      5    0.0   51.0   51.0     2626   
14513        724      5    0.0   51.0   51.0     2602   

                                                    data  jetmet-jetmet  
0      [4055.0, 2895.0, 735.0, 212.0, 46.0, 17.0, 9.0...           True  
1      [4252.0, 3101.0, 772.0, 222.0, 61.0, 19.0, 8.0...           True  
2      [4110.0, 2974.0, 818.0, 228.0, 58.0, 19.0, 15....           True  
3      [4156.0, 3053.0, 812.0, 204.0, 44.0, 17.0, 7.0...           True  
4      [4053.0, 3006.0, 783.0, 222.0, 60.0, 15.0, 7.0...           True  
...                                                  ...            ...  
14509  [1132.0, 957.0, 273.0, 99.0, 40.0, 13.0, 1.0, ...           True  
14510  [1169.0, 1046.0, 267.0, 100.0, 39.0, 13.0, 3.0...           True  
14511  [1171.0, 989.0, 293.0, 114.0, 48.0, 2.0, 1.0, ...           True  
14512  [1225.0, 960.0, 289.0, 93.0, 35.0, 14.0, 3.0, ...           True  
14513  [1190.0, 994.0, 257.0, 107.0, 33.0, 11.0, 4.0,...           True  

[14514 rows x 13 columns]

In [12]:
train_data = joint_data[["run_number", "data", "jetmet-jetmet"]]
train_data = train_data.rename(columns={'jetmet-jetmet': 'label'})
train_data

run_number                                               data  label
0          360950  [4055.0, 2895.0, 735.0, 212.0, 46.0, 17.0, 9.0...   True
1          360950  [4252.0, 3101.0, 772.0, 222.0, 61.0, 19.0, 8.0...   True
2          360950  [4110.0, 2974.0, 818.0, 228.0, 58.0, 19.0, 15....   True
3          360950  [4156.0, 3053.0, 812.0, 204.0, 44.0, 17.0, 7.0...   True
4          360950  [4053.0, 3006.0, 783.0, 222.0, 60.0, 15.0, 7.0...   True
...           ...                                                ...    ...
14509      386642  [1132.0, 957.0, 273.0, 99.0, 40.0, 13.0, 1.0, ...   True
14510      386642  [1169.0, 1046.0, 267.0, 100.0, 39.0, 13.0, 3.0...   True
14511      386642  [1171.0, 989.0, 293.0, 114.0, 48.0, 2.0, 1.0, ...   True
14512      386642  [1225.0, 960.0, 289.0, 93.0, 35.0, 14.0, 3.0, ...   True
14513      386642  [1190.0, 994.0, 257.0, 107.0, 33.0, 11.0, 4.0,...   True

[14514 rows x 3 columns]

In [13]:
data_arr = np.vstack(train_data.data)
data_arr

array([[4055., 2895.,  735., ...,    0.,    0.,    0.],
       [4252., 3101.,  772., ...,    0.,    0.,    0.],
       [4110., 2974.,  818., ...,    0.,    0.,    0.],
       ...,
       [1171.,  989.,  293., ...,    0.,    0.,    0.],
       [1225.,  960.,  289., ...,    0.,    0.,    0.],
       [1190.,  994.,  257., ...,    0.,    0.,    0.]])

In [14]:
label_arr = train_data.label.to_numpy().astype(np.float32)
label_arr

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [15]:
run_arr = train_data.run_number.to_numpy().astype(np.int32)
run_arr

array([360950, 360950, 360950, ..., 386642, 386642, 386642], dtype=int32)

In [16]:
unique, counts = np.unique(label_arr, return_counts=True)
dict(zip(unique, counts))

{np.float32(0.0): np.int64(2422), np.float32(1.0): np.int64(12092)}

In [17]:
os.makedirs("../data", exist_ok=True)
np.save(f"../data/data_runregistry_merged.npy", data_arr)
np.save(f"../data/label_runregistry_merged.npy", label_arr)
np.save(f"../data/runs_runregistry_merged.npy", run_arr)